### ISSUE TITLE
Does yara support non-intel architectures?

### ISSUE THREAD

**Issue by vt-alt** [VirusTotal/yara#1433]
I tried do package yara for ALT Linux, but it fail tests on aarch64, arm32, and powerpc architectures.

```
builder@aarch64:~/RPM/BUILD/yara-4.0.2$ make check
./build-aux/test-driver: line 109: 1644743 Segmentation fault      "$@" > $log_file 2>&1
FAIL: test-rules
```

```
builder@aarch64:~/RPM/BUILD/yara-4.0.2$ gdb -q -batch -ex r -ex bt ./test-rules
Missing separate debuginfo for /lib64/libcrypto.so.1.1
Try to install the hash file /usr/lib/debug/.build-id/e4/9bf2424fef763bcd8ab671e28cb9d22b3b4c05.debug
Missing separate debuginfo for /usr/lib64/libprotobuf-c.so.1
Try to install the hash file /usr/lib/debug/.build-id/e4/38888ea22abfc9eb8b2058161db339a9943b08.debug
Missing separate debuginfo for /usr/lib64/libmagic.so.1
Try to install the hash file /usr/lib/debug/.build-id/d5/1913d2394aad7b13ea494ed88b3f1b4ab7c984.debug
Missing separate debuginfo for /usr/lib64/libjansson.so.4
Try to install the hash file /usr/lib/debug/.build-id/56/32527cd49a5ad89ee82603f1ede8910cf22b88.debug
Missing separate debuginfo for /lib64/libpthread.so.0
Try to install the hash file /usr/lib/debug/.build-id/ba/2893a0bbd4666d2d471c3deb8bda15ba50443c.debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Missing separate debuginfo for /lib64/libz.so.1
Try to install the hash file /usr/lib/debug/.build-id/17/80123ddd8bfc621aaf5c65396c13bc28843884.debug

Program received signal SIGSEGV, Segmentation fault.
__GI__IO_fread (buf=0xaaaaaab68e10, size=size@entry=1, count=count@entry=1, fp=0x0) at iofread.c:42
42        _IO_acquire_lock (fp);
#0  __GI__IO_fread (buf=0xaaaaaab68e10, size=size@entry=1, count=count@entry=1, fp=0x0) at iofread.c:42
#1  0x0000aaaaaaac81f0 in fread (__stream=<optimized out>, __n=1, __size=1, __ptr=<optimized out>) at /usr/include/bits/stdio2.h:302
#2  yy_get_next_buffer (yyscanner=yyscanner@entry=0xaaaaaab6a570) at re_lexer.c:1607
#3  0x0000aaaaaaac8418 in input (yyscanner=yyscanner@entry=0xaaaaaab6a570) at re_lexer.c:1741
#4  0x0000aaaaaaac8c90 in read_escaped_char (yyscanner=yyscanner@entry=0xaaaaaab6a570, escaped_char=escaped_char@entry=0xffffffffc4b7 "") at re_lexer.l:561
#5  0x0000aaaaaaac9164 in re_yylex (yylval_param=yylval_param@entry=0xffffffffc570, yyscanner=yyscanner@entry=0xaaaaaab6a570, lex_env=lex_env@entry=0xffffffffce38) at re_lexer.l:284
#6  0x0000aaaaaaafe490 in re_yyparse (yyscanner=0xaaaaaab6a570, lex_env=lex_env@entry=0xffffffffce38) at re_grammar.c:1256
#7  0x0000aaaaaaac97f0 in yr_parse_re_string (re_string=re_string@entry=0xaaaaaab62b48 "\\x", re_ast=re_ast@entry=0xffffffffd168, error=error@entry=0xffffffffd188) at re_lexer.l:636
#8  0x0000aaaaaaac5c54 in yr_re_parse (re_string=re_string@entry=0xaaaaaab62b48 "\\x", re_ast=re_ast@entry=0xffffffffd168, error=error@entry=0xffffffffd188) at re.c:246
#9  0x0000aaaaaaafcbb8 in yr_parser_reduce_string_declaration (yyscanner=yyscanner@entry=0xaaaaaab61c30, modifier=..., identifier=0xaaaaaab692d0 "$a", str=0xaaaaaab62b40, string_ref=string_ref@entry=0xffffffffd658) at parser.c:675
#10 0x0000aaaaaaaef620 in yara_yyparse (yyscanner=0xaaaaaab61c30, compiler=compiler@entry=0xaaaaaab63640) at grammar.y:614
#11 0x0000aaaaaaac26a0 in yr_lex_parse_rules_string (rules_string=rules_string@entry=0xaaaaaab083c0 "rule test { strings: $a = /\\x/ condition: $a }", compiler=0xaaaaaab63640) at lexer.l:893
#12 0x0000aaaaaaabf4f8 in yr_compiler_add_string (compiler=<optimized out>, rules_string=rules_string@entry=0xaaaaaab083c0 "rule test { strings: $a = /\\x/ condition: $a }", namespace_=namespace_@entry=0x0) at compiler.c:628
#13 0x0000aaaaaaabc520 in compile_rule (string=string@entry=0xaaaaaab083c0 "rule test { strings: $a = /\\x/ condition: $a }", rules=rules@entry=0xfffffffff420) at tests/util.c:140
#14 0x0000aaaaaaab7388 in test_re () at tests/test-rules.c:2027
#15 0x0000aaaaaaab0420 in main (argc=<optimized out>, argv=<optimized out>) at tests/test-rules.c:2829
builder@aarch64:~/RPM/BUILD/yara-4.0.2$
```

**Comment by wxsBSD** [comment]
This was fixed recently but hasn’t made it into a release yet.

**Comment by vt-alt** [comment]
Thanks for the answer!

**Comment by vt-alt** [comment]
I hope new release will be soon. There is much time passed since previous one. Thanks,

**Comment by ozanh** [comment]
Is this bug fixed? v4.0.5 under Ubuntu 20.04 arm64 still throws this error.

**Comment by plusvic** [comment]
@ozanh can you try with the latest commit from the master branch?

**Comment by ozanh** [comment]
master branch with latest commit works like a charm :+1:  Thank you @plusvic
